-- create table users (
--     id                    bigserial,
--     username              varchar(30) not null,
--     password              varchar(80) not null,
--     email                 varchar(50) unique,
--     name                  varchar(255) not null,
--     surname               varchar(255) not null,
--     created_at            timestamp default current_timestamp,
--     updated_at            timestamp default current_timestamp,
--     primary key (id)
-- );

-- create table roles (
--     id                    serial,
--     name                  varchar(50) not null,
--     created_at            timestamp default current_timestamp,
--     updated_at            timestamp default current_timestamp,
--     primary key (id)
-- );
--
-- CREATE TABLE users_roles (
--     user_id               bigint not null,
--     role_id               int not null,
--     primary key (user_id, role_id),
--     foreign key (user_id) references users (id),
--     foreign key (role_id) references roles (id)
-- );
